// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultiasset, StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface BlockCarousel {
  assets: StoryblokMultiasset;
  speed?: number;
  component: "block_carousel";
  _uid: string;
}

export interface Page {
  text?: StoryblokRichtext;
  blocks?: BlockCarousel[];
  tab_seo?: unknown;
  seo_title?: string;
  seo_description?: string;
  seo_image?: StoryblokAsset;
  component: "page";
  _uid: string;
}

export interface Settings {
  site_name?: string;
  component: "settings";
  _uid: string;
}

export type ContentType = Page | Settings;
